### ISSUE TITLE
Difference between atrophy and degeneration

### ISSUE THREAD

**Issue by mnk77** [obophenotype/mammalian-phenotype-ontology#2121]
Do we need both 
optic nerve atrophy [MP:0001059] -acquired diminution of the size of the second cranial nerve which is responsible for conveying visual information from the retina to the brain, associated with wasting as from death and reabsorbtion of cells, diminished cellular proliferation, decreased cellular volume, pressure, ischemia, malnutrition, reduced function or malfunction, or hormonal changes

optic nerve degeneration [MP:0006219] - retrogressive pathologic change of the optic nerve

The definitions and concepts seem very similar. What is the different between the two other than using the term used by the publication?

**Comment by cmungall** [comment]
I can't find my notes, perhaps @mellybelly or @cindyJax remembers, we 
have discussed atrophy vs degeneration at a previous meeting, and we 
decided we needed a distinction between an active pathological mechanism 
vs wasting away. These are the core definitions we came up with:

  * PATO:0001623 ! atrophied [DEF: "A size quality inhering in a bearer 
by virtue of a part or parts of the bearer's being decreased in size due 
to reduction in tissue mass through wasting."]
  * PATO:0000639 ! degenerate [DEF: "A structural quality inhering in a 
bearer whose structure deteriorates or is lost over time due to an 
active pathological process."]

This doesn't mean that the concepts aren't easily confused and the terms 
used interchangeably. It looks as if the MP definitions are consistent 
with PATO, but I might try and simplify the definitions a bit. I'm not a 
big fan of repeating the definition of the anatomical structure, I would 
just say "optic nerve" (possibly including a description of this after 
the first period). E.g.


acquired diminution of the size of the optic nerve associated with 
wasting
as from death and reabsorbtion of cells, diminished cellular 
proliferation, decreased cellular volume, pressure, ischemia, 
malnutrition, reduced function or malfunction, or hormonal changes

An active retrogressive pathologic deterioration of the optic nerve, due 
to processes such as ...

**Comment by cindyJax** [comment]
I revised the text definitions for these two terms. In this case, the eye research community does confound these terms quite a bit in the literature, but I think the distinction is important.
