### ISSUE TITLE
NTR: abnormal airway chloride transport

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/mammalian-phenotype-ontology#2123]
parent: MP_0001765 abnormal ion homeostasis
def: aberrant measurable or observable characteristic related to the transport of chloride in the respiratory airway
logical def:
'has part' some 
    (quality
     and ('inheres in' some 
        ('chloride transport'
         and ('part of' some 'respiratory airway')))
     and ('has modifier' some abnormal))

NTR: decreased airway chloride transport
parent: abnormal airway chloride transport
def: decreased measurable or observable characteristic related to the transport of chloride in the respiratory airway
logical def:
'has part' some 
    ('decreased rate'
     and ('inheres in' some 
        ('chloride transport'
         and ('part of' some 'respiratory airway')))
     and ('has modifier' some abnormal))

**Comment by cindyJax** [comment]
Terms are better labeled and defined as 

abnormal respiratory transepithelial chloride transport
decreased respiratory transepithelial chloride transport

because it is the epithelium that transports the chloride ion, not the airway itself.


logical def:
'has part' some
(quality
and ('inheres in' some
('transepithelial chloride transport'
and ('part of' some 'respiratory epithelium')))
and ('has modifier' some abnormal))

etc..

**Comment by nicolevasilevsky** [comment]
sounds good!

**Comment by cindyJax** [comment]
New terms added:
abnormal respiratory epithelial chloride transmembrane transport MP_0014027

decreased respiratory epithelial chloride transmembrane transport MP_0014028

increased respiratory epithelial chloride transmembrane transport MP_0014029
