### ISSUE TITLE
 Type II pneumocyte hyperplasia

### ISSUE THREAD

**Issue by anna-anagnostop** [obophenotype/mammalian-phenotype-ontology#3353]
Consider adding new term "type II pneumocyte hyperplasia" as a child of abnormal type II pneumocyte morphology MP:0002275

type II pneumocyte hyperplasia
DEF: overdevelopment or increased size of type II pneumocytes characterized by qualitative morphologic alterations, including cuboidal shapes, increased nucleocytoplasmic ratio, enlarged nuclei, prominent nucleoli, and various alterations in their nuclear chromatin; develops as a response to alveolar injury in various pulmonary disorders, esp. in the setting of inflammation and interstitial fibrosis and during the healing phase of diffuse alveolar damage
SOURCE: PMID:11079017, HP:0033328

Annotations made to genotypes MGI:3037342, MGI:3606939, MGI:6455041 under increased type II pneumocyte number MP:0010810 

Related to COVID-19 lung pathology PMID: 32427582, https://doi.org/10.1038/s41379-020-00661-1

**Comment by sbello** [comment]
I'm concerned about using hyperplasia in a way it isn't usually used.
Questions
1. Is the morphology description in PMID:11079017 really a description of the normal morphology of type II cells?
2. Where did the HPO definition come from? Was it reviewed by a respiratory specialist?

I think we need a clearer definition of what a normal type II cell is. 

 PMID:11079017 doesn't mention size
"The diagnosis of hyperplasia of type II alveolar epithelial cells in human lung specimens is usually based on the finding of (1) clusters of these cells, instead of cells occurring singly, and (2) qualitative morphologic alterations, including cuboidal shapes, increased nucleocytoplasmic ratio, enlarged nuclei, prominent nucleoli, and various alterations in their nuclear chromatin.21,22 "

**Comment by anna-anagnostop** [comment]
Added new term:
reactive type II pneumocyte hyperplasia MP:0031238 (as a child of increased type II cell number MP:0010810)
