### ISSUE TITLE
add abnormal prenatal movement

### ISSUE THREAD

**Issue by sbello** [obophenotype/mammalian-phenotype-ontology#3784]
add terms for:
abnormal prenatal movement
absent prenatal movement - annotations are currently to absent spontaneous movement
see HP:0001557 
phenotype for Cornelia de Lange syndrome

**Comment by anna-anagnostop** [comment]
abnormal prenatal movement
DEF: any abnormality in the quantity or strength of movements of a fetus within the uterus
SYN: abnormal fetal movement (narrow)

For a definition of fetal movement see https://www.definitions.net/definition/fetal+movement:

"Fetal movement refers to motion of a fetus caused by its own muscle activity. Locomotor activity begins during the late embryological stage, and changes in nature throughout development. Muscles begin to move as soon as they are innervated. These first movements are not reflexive, but arise from self-generated nerve impulses originating in the spinal cord. As the nervous system matures, muscles can move in response to stimuli. Generally speaking, fetal motility can be classified as either elicited or spontaneous, and spontaneous movements may be triggered by either the spine or the brain."

**Comment by anna-anagnostop** [comment]
absent prenatal movement
DEF: absence of any movements of a developing organism within the uterus

Place abnormal prenatal movement directly under abnormal motor capabilities/coordination/movement

**Comment by sbello** [comment]
make abnormal spontaneous fetal mouth movement (MP:0031464) a child of the new term
